name: Build Image, Push to Docker Hub

on:
  workflow_dispatch:
    branches:
      - master

jobs:
  build-push-docker-hub:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.2.0

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - id: docker_build_push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: pitop/mdbook:latest

      - name: Show image digest
        run: echo ${{ steps.docker_build_push.outputs.digest }}
